# Generated by Django 3.2 on 2021-04-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_albulm_musician'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('shirt_size', models.CharField(choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], max_length=1)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Person',
            },
        ),
    ]
