# Generated by Django 3.2 on 2021-04-19 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210419_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['age']},
        ),
    ]
